FROM python:3.12-slim

WORKDIR /onlineback

RUN set -eux && \
  	apt-get update &&  \
  	apt-get upgrade -y && \
  	apt-get install -y --no-install-recommends \
        build-essential \  
        libpq5 && \
    rm -rf /var/lib/apt/lists/* && \
	groupadd \
          --system \
       onlineback && \
      useradd \
          --system \
      onlineback \
          -g \
      onlineback 